public class TelegramBotChatWrapper {
    public final Long id;
    public final String type;
    public final String title;
    public final String username;
    public final String first_name;
    public final String last_name;
    public final String description;
    public final String invite_link;
    public final TelegramBotMessageWrapper pinned_message;
    public final Integer slow_mode_delay;
    public final String sticker_set_name;
    public final Boolean can_set_sticker_set;
}
