public class HttpConstants {
    public static String METHOD_POST = 'POST';

    public static String HEADER_NAME_CONTENT_TYPE = 'Content-Type';

    public static String HEADER_VALUE_CONTENT_TYPE_JSON = 'application/json';

    public static Integer STATUS_CODE_SUCCESS = 200;
    public static Integer STATUS_CODE_BAD_REQUEST = 400;

    public static String RESPONSE_OK = 'OK';
    public static String RESPONSE_ERROR = 'ERROR';
}
