name: Enforce Branch Naming

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: 'Validate Branch Name'
        uses: deepakputhraya/action-branch-name@master
        with:
          allowed_prefixes: 'feature,bugfix,release'
          min_length: 6
